In [33]:
!pip install yfinance pandas numpy

Requirement already satisfied: yfinance in c:\users\hp\anaconda3\lib\site-packages (1.0)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (4.25.3)
Requirement already satisfied: websockets>=13.0 in c:\users\hp\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\hp\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\hp\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2024.12.14)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)

In [34]:
# Import libraries
import yfinance as yf
import pandas as pd
# Choose companies 
stocks = ['AAPL', 'MSFT', 'JNJ', 'XOM', 'BTC-USD']
# Download price data
data = yf.download(
    stocks,
    start='2019-01-01',
    end='2024-12-31',
    auto_adjust=True
)

data.head()

[*********************100%***********************]  5 of 5 completed

Price           Close                                                 \
Ticker           AAPL      BTC-USD         JNJ       MSFT        XOM
Date
2019-01-01        NaN  3843.520020         NaN        NaN        NaN
2019-01-02  37.538822  3943.409424  104.942825  94.612595  50.335125
2019-01-03  33.799690  3836.741211  103.275253  91.131996  49.562290
2019-01-04  35.242561  3857.717529  105.008545  95.370483  51.389641
2019-01-05        NaN  3845.194580         NaN        NaN        NaN

Price            High                                                 ...  \
Ticker           AAPL      BTC-USD         JNJ       MSFT        XOM  ...
Date                                                                  ...
2019-01-01        NaN  3850.913818         NaN        NaN        NaN  ...
2019-01-02  37.759892  3947.981201  105.460356  95.202049  50.465134  ...
2019-01-03  34.638799  3935.685059  105.370005  93.742451  50.739591  ...
2019-01-04  35.311499  3865.934570  105.682144  95.913160  51.476310  ...
2019-01-05        NaN  3904.903076         NaN        NaN        NaN  ...

Price            Open                                                 \
Ticker           AAPL      BTC-USD         JNJ       MSFT        XOM
Date
2019-01-01        NaN  3746.713379         NaN        NaN        NaN
2019-01-02  36.818568  3849.216309  105.254988  93.143630  48.645006
2019-01-03  34.225186  3931.048584  105.263210  93.658240  50.559023
2019-01-04  34.355912  3832.040039  104.425302  93.302705  50.299009
2019-01-05        NaN  3851.973877         NaN        NaN        NaN

Price            Volume
Ticker             AAPL     BTC-USD        JNJ        MSFT         XOM
Date
2019-01-01          NaN  4324200990        NaN         NaN         NaN
2019-01-02  148158800.0  5244856836  7631700.0  35329300.0  16727200.0
2019-01-03  365248800.0  4530215219  8654500.0  42579100.0  13866100.0
2019-01-04  234428400.0  4847965467  8831700.0  44060600.0  16043600.0
2019-01-05          NaN  5137609824        NaN         NaN         NaN

[5 rows x 25 columns]

In [35]:
# Keep price only
prices = data['Close']
prices.head()

Ticker           AAPL      BTC-USD         JNJ       MSFT        XOM
Date
2019-01-01        NaN  3843.520020         NaN        NaN        NaN
2019-01-02  37.538822  3943.409424  104.942825  94.612595  50.335125
2019-01-03  33.799690  3836.741211  103.275253  91.131996  49.562290
2019-01-04  35.242561  3857.717529  105.008545  95.370483  51.389641
2019-01-05        NaN  3845.194580         NaN        NaN        NaN

In [36]:
# Clean missing data
prices = prices.ffill()
prices.isnull().sum()

Ticker
AAPL       1
BTC-USD    0
JNJ        1
MSFT       1
XOM        1
dtype: int64

In [37]:
prices = prices.ffill().bfill()

In [38]:
prices.isnull().sum()

Ticker
AAPL       0
BTC-USD    0
JNJ        0
MSFT       0
XOM        0
dtype: int64

In [39]:
# Save clean data
prices.to_csv('clean_stock_prices.csv')

print("Week 1 completed successfully!")

Week 1 completed successfully!

# WEEK 2

<!-- Week 2 -->

In [42]:
import pandas as pd
import numpy as np

# Load clean price data
prices = pd.read_csv('clean_stock_prices.csv', index_col=0, parse_dates=True)

prices.head()

                 AAPL      BTC-USD         JNJ       MSFT        XOM
Date
2019-01-01  37.538822  3843.520020  104.942825  94.612595  50.335125
2019-01-02  37.538822  3943.409424  104.942825  94.612595  50.335125
2019-01-03  33.799690  3836.741211  103.275253  91.131996  49.562290
2019-01-04  35.242561  3857.717529  105.008545  95.370483  51.389641
2019-01-05  35.242561  3845.194580  105.008545  95.370483  51.389641

In [43]:
# Calculate Daily Returns
# (How much did the price change compared to yesterday?)
daily_returns = prices.pct_change()

daily_returns.head()

                AAPL   BTC-USD       JNJ      MSFT       XOM
Date
2019-01-01       NaN       NaN       NaN       NaN       NaN
2019-01-02  0.000000  0.025989  0.000000  0.000000  0.000000
2019-01-03 -0.099607 -0.027050 -0.015890 -0.036788 -0.015354
2019-01-04  0.042689  0.005467  0.016783  0.046509  0.036870
2019-01-05  0.000000 -0.003246  0.000000  0.000000  0.000000

In [44]:
# Cleaning
daily_returns = daily_returns.dropna()

In [45]:
daily_returns.head()

                AAPL   BTC-USD       JNJ      MSFT       XOM
Date
2019-01-02  0.000000  0.025989  0.000000  0.000000  0.000000
2019-01-03 -0.099607 -0.027050 -0.015890 -0.036788 -0.015354
2019-01-04  0.042689  0.005467  0.016783  0.046509  0.036870
2019-01-05  0.000000 -0.003246  0.000000  0.000000  0.000000
2019-01-06  0.000000  0.060189  0.000000  0.000000  0.000000

In [46]:
# Calculate Volatility (Risk)
volatility = daily_returns.std()

volatility

AAPL       0.016138
BTC-USD    0.033896
JNJ        0.010012
MSFT       0.015169
XOM        0.016862
dtype: float64

In [47]:
volatility_percent = volatility * 100
volatility_percent

AAPL       1.613751
BTC-USD    3.389602
JNJ        1.001214
MSFT       1.516941
XOM        1.686204
dtype: float64

In [48]:
# Monte Carlo Simulation
stock = 'AAPL'
# stock = 'MSFT'
# stock = 'BTC-USD'

In [49]:
mean_return = daily_returns[stock].mean()
std_return = daily_returns[stock].std()

mean_return, std_return

(0.000998230086838155, 0.016137513694031453)

In [50]:
num_simulations = 1000
num_days = 252  # 1 trading year

simulated_prices = []

last_price = prices[stock].iloc[-1]

for i in range(num_simulations):
    daily_simulated_returns = np.random.normal(mean_return, std_return, num_days)
    price_path = last_price * (1 + daily_simulated_returns).cumprod()
    simulated_prices.append(price_path)

In [51]:
mc_results = []

for sim_no, path in enumerate(simulated_prices):
    for day, value in enumerate(path):
        mc_results.append([sim_no + 1, day + 1, value])

mc_df = pd.DataFrame(
    mc_results,
    columns=["Simulation", "Day", "Portfolio_Value"]
)

In [52]:
mc_df

        Simulation  Day  Portfolio_Value
0                1    1       254.905211
1                1    2       251.926034
2                1    3       249.216568
3                1    4       249.677672
4                1    5       259.363835
...            ...  ...              ...
251995        1000  248       323.370689
251996        1000  249       325.423454
251997        1000  250       328.791362
251998        1000  251       324.586661
251999        1000  252       325.919106

[252000 rows x 3 columns]

In [75]:
# Calculate Value at Risk (VaR)

# Calculate final prices:(extracts the last (final-day) price)
final_prices = [path[-1] for path in simulated_prices]

In [77]:
# Calculate VaR:
var_95 = np.percentile(final_prices, 5)

print("Value at Risk (95%):", var_95)

Value at Risk (95%): 212.03677005600085

In [79]:
import pandas as pd

var_df = pd.DataFrame({
    "Confidence_Level": ["95%"],
    "VaR_Value": [var_95]
})
var_df.to_csv("var_summary.csv", index=False)

In [81]:
# Portfolio Prices / Returns

In [83]:
daily_returns.to_csv("daily_returns.csv", index=True)

In [85]:
# Rolling Volatility

In [87]:
# Recalculate rolling volatility properly
rolling_vol = daily_returns.rolling(window=30).std()

# Convert index (Date) into a column
rolling_vol = rolling_vol.reset_index()

# Convert from wide to long format (BEST for Tableau)
rolling_vol_long = rolling_vol.melt(
    id_vars="Date",
    var_name="Stock",
    value_name="Rolling_Volatility"
)

# Remove initial NaN rows (first 29 days)
rolling_vol_long = rolling_vol_long.dropna()

# Save clean file
rolling_vol_long.to_csv(
    "rolling_volatility.csv",
    index=False,
    encoding="utf-8"
)

In [89]:
# Monte Carlo Simulation

In [91]:
mc_df.to_csv("monte_carlo_simulation.csv", index=False)

In [94]:
var_df.to_csv("var_summary.csv", index=False)

In [106]:
corr = daily_returns.corr()
corr

             AAPL   BTC-USD       JNJ      MSFT       XOM
AAPL     1.000000  0.227817  0.361236  0.734882  0.291315
BTC-USD  0.227817  1.000000  0.082629  0.268858  0.151581
JNJ      0.361236  0.082629  1.000000  0.371955  0.294397
MSFT     0.734882  0.268858  0.371955  1.000000  0.253459
XOM      0.291315  0.151581  0.294397  0.253459  1.000000

In [108]:
corr.to_csv("correlation_matrix.csv")

In [110]:
# correlation = log_returns.corr()
# correlation

In [96]:
# # correlation matrix
# log_returns = np.log(data / data.shift(1))
# log_returns = log_returns.dropna()

In [112]:
# log_returns.head()

In [102]:
# correlation.to_csv("correlation_matrix.csv")